# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bookingID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('eventID', models.IntegerField()),
                ('qrCode', models.CharField(max_length=20)),
                ('confirmed', models.BooleanField()),
                ('checkinTime', models.TimeField()),
                ('checkinDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('countyID', models.AutoField(primary_key=True, serialize=False)),
                ('countyName', models.CharField(choices=[(b'antrim', b'Antrim'), (b'armagh', b'Armagh'), (b'carlow', b'Carlow'), (b'cavan', b'Cavan'), (b'clare', b'Clare'), (b'cork', b'Cork'), (b'derry', b'Derry'), (b'donegal', b'Donegal'), (b'down', b'Down'), (b'dublin', b'Dublin'), (b'fermanagh', b'Fermanagh'), (b'galway', b'Galway'), (b'kerry', b'Kerry'), (b'kildare', b'Kildare'), (b'kilkenny', b'Kilkenny'), (b'laois', b'Laois'), (b'leitrim', b'Leitrim'), (b'limerick', b'Limerick'), (b'longford', b'Longford'), (b'louth', b'Louth'), (b'mayo', b'Mayo'), (b'meath', b'Meath'), (b'monaghan', b'Monaghan'), (b'offaly', b'Offaly'), (b'roscommon', b'Roscommon'), (b'sligo', b'Sligo'), (b'tipperary', b'Tipperary'), (b'tyrone', b'Tyrone'), (b'waterford', b'Waterford'), (b'westmeath', b'Westmeath'), (b'wexford', b'Wexford'), (b'wicklow', b'Wicklow')], max_length=9)),
                ('province', models.CharField(choices=[(b'connacht', b'Connacht'), (b'leinster', b'Leinster'), (b'munster', b'Munster'), (b'ulster', b'Ulster')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('eventDescription', models.TextField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('venueID', models.IntegerField()),
                ('season', models.CharField(choices=[(b'spring', b'Spring'), (b'summer', b'Summer'), (b'autumn', b'Autumn'), (b'winter', b'Winter')], max_length=6)),
                ('notesID', models.IntegerField()),
                ('availability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('notesID', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=50)),
                ('dataType', models.CharField(max_length=10)),
                ('noteDescription', models.TextField()),
                ('dateAdded', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=b'test', max_length=40)),
                ('last_name', models.CharField(default=b'test', max_length=40)),
                ('age', models.CharField(default=b'test', max_length=40)),
                ('telephone', models.CharField(default=b'test', max_length=40)),
                ('addr_line_1', models.CharField(default=b'test', max_length=120)),
                ('addr_line_2', models.CharField(default=b'test', max_length=120)),
                ('county', models.CharField(default=b'test', max_length=40)),
                ('country', models.CharField(default=b'test', max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('userAddress', models.TextField()),
                ('userCounty', models.CharField(choices=[(b'antrim', b'Antrim'), (b'armagh', b'Armagh'), (b'carlow', b'Carlow'), (b'cavan', b'Cavan'), (b'clare', b'Clare'), (b'cork', b'Cork'), (b'derry', b'Derry'), (b'donegal', b'Donegal'), (b'down', b'Down'), (b'dublin', b'Dublin'), (b'fermanagh', b'Fermanagh'), (b'galway', b'Galway'), (b'kerry', b'Kerry'), (b'kildare', b'Kildare'), (b'kilkenny', b'Kilkenny'), (b'laois', b'Laois'), (b'leitrim', b'Leitrim'), (b'limerick', b'Limerick'), (b'longford', b'Longford'), (b'louth', b'Louth'), (b'mayo', b'Mayo'), (b'meath', b'Meath'), (b'monaghan', b'Monaghan'), (b'offaly', b'Offaly'), (b'roscommon', b'Roscommon'), (b'sligo', b'Sligo'), (b'tipperary', b'Tipperary'), (b'tyrone', b'Tyrone'), (b'waterford', b'Waterford'), (b'westmeath', b'Westmeath'), (b'wexford', b'Wexford'), (b'wicklow', b'Wicklow')], max_length=9)),
                ('userCountry', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1)),
                ('language', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('venueID', models.AutoField(primary_key=True, serialize=False)),
                ('venueAddress', models.TextField()),
                ('venueCounty', models.CharField(choices=[(b'antrim', b'Antrim'), (b'armagh', b'Armagh'), (b'carlow', b'Carlow'), (b'cavan', b'Cavan'), (b'clare', b'Clare'), (b'cork', b'Cork'), (b'derry', b'Derry'), (b'donegal', b'Donegal'), (b'down', b'Down'), (b'dublin', b'Dublin'), (b'fermanagh', b'Fermanagh'), (b'galway', b'Galway'), (b'kerry', b'Kerry'), (b'kildare', b'Kildare'), (b'kilkenny', b'Kilkenny'), (b'laois', b'Laois'), (b'leitrim', b'Leitrim'), (b'limerick', b'Limerick'), (b'longford', b'Longford'), (b'louth', b'Louth'), (b'mayo', b'Mayo'), (b'meath', b'Meath'), (b'monaghan', b'Monaghan'), (b'offaly', b'Offaly'), (b'roscommon', b'Roscommon'), (b'sligo', b'Sligo'), (b'tipperary', b'Tipperary'), (b'tyrone', b'Tyrone'), (b'waterford', b'Waterford'), (b'westmeath', b'Westmeath'), (b'wexford', b'Wexford'), (b'wicklow', b'Wicklow')], max_length=9)),
                ('venueCountry', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('venueType', models.CharField(choices=[(b'indoor', b'Indoor'), (b'outdoor', b'Outdoor')], max_length=7)),
            ],
        ),
    ]
