# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 01:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('constellation', '0002_remove_event_youtubevideoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='youtubeVideoID',
            field=models.TextField(default=datetime.datetime(2016, 3, 8, 1, 38, 10, 997292, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
