# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constellation', '0003_event_youtubevideoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='youtubeVideoID',
        ),
    ]
