# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellation', '0004_remove_event_youtubevideoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='youtubeVideoID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
