# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellation', '0005_event_youtubevideoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='youtubeVideoID',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
